add_newline = true

# ----------------------------------------------------
# format
# ----------------------------------------------------
format = """
${custom.hostname}\
$directory\
$git_branch\
$git_status\
$direnv\
$python\
$aws\
${custom.gcloud}\
$fill\
$cmd_duration\

$character\
"""

# Enable if it appears on the same line as the command
# right_format = """
# $cmd_duration\
# $time\
# """

# ----------------------------------------------------
# left module
# ----------------------------------------------------
[python]
format = "[|](fg:#75715E)[ $virtualenv ]($style)"
style = "fg:#E6DB74"

[fill]
symbol = ' '

[directory]
truncation_length = 6
truncation_symbol = ' '
truncate_to_repo = false
home_symbol = '~'
read_only = ' 󰌾'
format = "[|](fg:#75715E)[ $path$read_only ]($style)"
style = 'fg:#AE81FF'
read_only_style = 'fg:#AE81FF'

[direnv]
disabled = false
format = "[|](fg:#75715E)[ $symbol$allowed ]($style)"
style = "fg:#A6E22E"

[git_branch]
symbol = ""
style = "fg:#66D9EF"
format = "[|](fg:#75715E)[ $symbol $branch]($style)"

[git_status]
style = "fg:#66D9EF"
format = "[ $all_status$ahead_behind ]($style)"

# ----------------------------------------------------
# right module
# ----------------------------------------------------
[cmd_duration]
min_time = 1
style = "fg:#FD971F"
format = "[ $duration ]($style)"

[time]
disabled = false
time_format = "%R"
format = '[[  $time](fg:#75715E)]($style)'

[custom.hostname]
when = "true"
command = "scutil --get LocalHostName 2>/dev/null || scutil --get ComputerName 2>/dev/null || hostnamectl --static 2>/dev/null || hostname -s 2>/dev/null || hostname"
format = "[󰌢 $output ]($style)"
style = "fg:#75715E"

# ----------------------------------------------------
# prompt module
# ----------------------------------------------------
[character]
vimcmd_symbol = '[V](bold #A6E22E) '

# ----------------------------------------------------
# AWS module
# ----------------------------------------------------
[aws]
format = "[|](fg:#75715E)[ $symbol $profile ]($style)"
symbol = "💭"
style = "fg:#E6DB74"

# ----------------------------------------------------
# GCP module
# ----------------------------------------------------
[gcloud]
disabled = true

[custom.gcloud]
when = "command -v gcloud && command -v terraform"
command = '''
f=~/.config/gcloud/configurations/config_$(cat ~/.config/gcloud/active_config 2>/dev/null || echo default)
a=$(perl -ne 'print $1 if /^account\s*=\s*[^@]*@(.+)/' "$f" 2>/dev/null)
p=$(perl -ne 'print $1 if /^project\s*=\s*(.+)/' "$f" 2>/dev/null)
[ -n "$a" ] && echo "☁️ ${a}(${p})"
'''
format = "[|](fg:#75715E)[ $output ]($style)"
style = "fg:#66D9EF"
